-- =============================================================================
-- SISTEMA CONTABLE AUTOMATIZADO - SCRIPT DEFINITIVO NO DESTRUCTIVO (POSTGRESQL 14+)
-- Sincronización 1:1 con Next.js + Auditoría e Historial Intacto (Sin DELETE)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. LIMPIEZA PREVENTIVA
-- -----------------------------------------------------------------------------
DROP VIEW IF EXISTS vista_balance_general CASCADE;
DROP VIEW IF EXISTS vista_estado_resultados CASCADE;
DROP VIEW IF EXISTS vista_estado_resultados_detalle CASCADE;
DROP VIEW IF EXISTS vista_balance_comprobacion CASCADE;
DROP VIEW IF EXISTS vista_libro_mayor CASCADE;
DROP VIEW IF EXISTS vista_libro_diario CASCADE;

DROP TABLE IF EXISTS cierre_contable CASCADE;
DROP TABLE IF EXISTS asiento_linea CASCADE;
DROP TABLE IF EXISTS asiento CASCADE;
DROP TABLE IF EXISTS catalogo_cuentas CASCADE;

-- -----------------------------------------------------------------------------
-- 2. TABLA: CATÁLOGO DE CUENTAS (lib/types.ts -> interface Cuenta)
-- -----------------------------------------------------------------------------
CREATE TABLE catalogo_cuentas (
    codigo VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('activo', 'pasivo', 'capital', 'gasto', 'ingreso')),
    naturaleza VARCHAR(20) NOT NULL CHECK (naturaleza IN ('deudora', 'acreedora')),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_codigo_digito CHECK (
        (codigo LIKE '1%' AND tipo = 'activo'  AND naturaleza = 'deudora') OR
        (codigo LIKE '2%' AND tipo = 'pasivo'  AND naturaleza = 'acreedora') OR
        (codigo LIKE '3%' AND tipo = 'capital' AND naturaleza = 'acreedora') OR
        (codigo LIKE '4%' AND tipo = 'gasto'   AND naturaleza = 'deudora') OR
        (codigo LIKE '5%' AND tipo = 'ingreso' AND naturaleza = 'acreedora')
    )
);

CREATE INDEX idx_catalogo_tipo ON catalogo_cuentas(tipo);
CREATE INDEX idx_catalogo_activa ON catalogo_cuentas(activa);

-- -----------------------------------------------------------------------------
-- 3. TABLA: ASIENTOS (CABECERA LIBRO DIARIO) (lib/types.ts -> interface Asiento)
-- -----------------------------------------------------------------------------
CREATE TABLE asiento (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero INT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    ejercicio INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INT,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL,
    tipo VARCHAR(20) NOT NULL DEFAULT 'OPERACION' CHECK (tipo IN ('APERTURA', 'OPERACION', 'AJUSTE', 'CIERRE')),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_asiento_fecha ON asiento(fecha);
CREATE INDEX idx_asiento_ejercicio ON asiento(ejercicio);

-- -----------------------------------------------------------------------------
-- 4. TABLA: LÍNEAS DEL ASIENTO (lib/types.ts -> interface AsientoLinea)
-- -----------------------------------------------------------------------------
CREATE TABLE asiento_linea (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asiento_id UUID NOT NULL REFERENCES asiento(id) ON DELETE CASCADE,
    linea_numero INT NOT NULL DEFAULT 1,
    cuenta_codigo VARCHAR(20) NOT NULL REFERENCES catalogo_cuentas(codigo) ON DELETE RESTRICT,
    debe NUMERIC(14, 2) NOT NULL DEFAULT 0.00 CHECK (debe >= 0),
    haber NUMERIC(14, 2) NOT NULL DEFAULT 0.00 CHECK (haber >= 0),
    CONSTRAINT uq_asiento_linea UNIQUE (asiento_id, linea_numero),
    CONSTRAINT chk_linea_exclusiva CHECK (
        (debe > 0 AND haber = 0) OR 
        (haber > 0 AND debe = 0)
    )
);

CREATE INDEX idx_linea_asiento ON asiento_linea(asiento_id);
CREATE INDEX idx_linea_cuenta ON asiento_linea(cuenta_codigo);

-- -----------------------------------------------------------------------------
-- 5. TABLA: HISTORIAL DE CIERRES CONTABLES (lib/types.ts -> interface CierreContable)
-- -----------------------------------------------------------------------------
CREATE TABLE cierre_contable (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ejercicio INT NOT NULL,
    fecha_cierre DATE NOT NULL DEFAULT CURRENT_DATE,
    concepto TEXT NOT NULL DEFAULT 'Cierre del ejercicio fiscal',
    total_ingresos NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_gastos NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    utilidad NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    cuenta_capital_codigo VARCHAR(20) NOT NULL REFERENCES catalogo_cuentas(codigo),
    asiento_cierre_id UUID NOT NULL REFERENCES asiento(id),
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cierre_ejercicio ON cierre_contable(ejercicio);
CREATE INDEX idx_cierre_fecha ON cierre_contable(fecha_cierre);

-- -----------------------------------------------------------------------------
-- 6. VISTAS DEL CICLO CONTABLE
-- -----------------------------------------------------------------------------

-- 5.1. Libro Diario consolidado (mantiene el orden cronológico y de renglones)
CREATE OR REPLACE VIEW vista_libro_diario AS
SELECT 
    a.id AS asiento_id,
    a.numero AS partida_numero,
    a.ejercicio,
    a.fecha,
    a.concepto,
    a.tipo AS tipo_asiento,
    al.linea_numero,
    c.codigo AS cuenta_codigo,
    c.nombre AS cuenta_nombre,
    c.tipo AS cuenta_tipo,
    c.naturaleza AS cuenta_naturaleza,
    al.debe,
    al.haber
FROM asiento a
JOIN asiento_linea al ON a.id = al.asiento_id
JOIN catalogo_cuentas c ON al.cuenta_codigo = c.codigo
ORDER BY a.fecha DESC, a.numero DESC, al.linea_numero ASC;

-- 5.2. Libro Mayor (lib/contabilidad.ts -> calcularMayor)
CREATE OR REPLACE VIEW vista_libro_mayor AS
SELECT 
    c.codigo AS cuenta_codigo,
    c.nombre AS cuenta_nombre,
    c.tipo AS cuenta_tipo,
    c.naturaleza AS cuenta_naturaleza,
    c.activa,
    ROUND(SUM(al.debe), 2) AS total_debe,
    ROUND(SUM(al.haber), 2) AS total_haber,
    ROUND(SUM(al.debe) - SUM(al.haber), 2) AS saldo_neto,
    CASE 
        WHEN ROUND(SUM(al.debe) - SUM(al.haber), 2) > 0 THEN 'deudora'
        WHEN ROUND(SUM(al.debe) - SUM(al.haber), 2) < 0 THEN 'acreedora'
        ELSE NULL 
    END AS naturaleza_saldo,
    CASE 
        WHEN c.naturaleza = 'deudora' THEN ROUND(SUM(al.debe) - SUM(al.haber), 2)
        ELSE ROUND(SUM(al.haber) - SUM(al.debe), 2)
    END AS saldo_normalizado
FROM catalogo_cuentas c
JOIN asiento_linea al ON c.codigo = al.cuenta_codigo
GROUP BY c.codigo, c.nombre, c.tipo, c.naturaleza, c.activa
HAVING SUM(al.debe) <> 0 OR SUM(al.haber) <> 0;

-- 5.3. Balance de Comprobación
CREATE OR REPLACE VIEW vista_balance_comprobacion AS
SELECT 
    cuenta_codigo,
    cuenta_nombre,
    cuenta_tipo,
    total_debe,
    total_haber,
    CASE WHEN saldo_neto > 0 THEN saldo_neto ELSE 0.00 END AS saldo_deudor,
    CASE WHEN saldo_neto < 0 THEN ABS(saldo_neto) ELSE 0.00 END AS saldo_acreedor
FROM vista_libro_mayor
ORDER BY cuenta_codigo ASC;

-- 5.4. Detalle Estado de Resultados (subgrupos por prefijos)
CREATE OR REPLACE VIEW vista_estado_resultados_detalle AS
SELECT 
    cuenta_codigo,
    cuenta_nombre,
    cuenta_tipo,
    CASE 
        WHEN cuenta_tipo = 'ingreso' AND LEFT(cuenta_codigo, 2) = '52' THEN 'ingresosFinancieros'
        WHEN cuenta_tipo = 'ingreso' THEN 'ventas'
        WHEN cuenta_tipo = 'gasto' AND LEFT(cuenta_codigo, 2) = '41' THEN 'costoVentas'
        WHEN cuenta_tipo = 'gasto' AND LEFT(cuenta_codigo, 2) = '43' THEN 'gastosFinancieros'
        WHEN cuenta_tipo = 'gasto' THEN 'gastosOperacion'
        ELSE NULL 
    END AS subgrupo,
    CASE 
        WHEN cuenta_tipo = 'ingreso' THEN ROUND(total_haber - total_debe, 2)
        WHEN cuenta_tipo = 'gasto' THEN ROUND(total_debe - total_haber, 2)
        ELSE 0.00
    END AS monto
FROM vista_libro_mayor
WHERE cuenta_tipo IN ('ingreso', 'gasto');

-- 5.5. Resumen Estado de Resultados en Cascada (lib/contabilidad.ts -> calcularEstadoResultados)
CREATE OR REPLACE VIEW vista_estado_resultados AS
WITH totales AS (
    SELECT 
        COALESCE(SUM(CASE WHEN subgrupo = 'ventas' THEN monto ELSE 0 END), 0.00) AS total_ventas,
        COALESCE(SUM(CASE WHEN subgrupo = 'costoVentas' THEN monto ELSE 0 END), 0.00) AS total_costo_ventas,
        COALESCE(SUM(CASE WHEN subgrupo = 'gastosOperacion' THEN monto ELSE 0 END), 0.00) AS total_gastos_operacion,
        COALESCE(SUM(CASE WHEN subgrupo = 'ingresosFinancieros' THEN monto ELSE 0 END), 0.00) AS total_ingresos_financieros,
        COALESCE(SUM(CASE WHEN subgrupo = 'gastosFinancieros' THEN monto ELSE 0 END), 0.00) AS total_gastos_financieros,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'ingreso' THEN monto ELSE 0 END), 0.00) AS total_ingresos,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'gasto' THEN monto ELSE 0 END), 0.00) AS total_gastos
    FROM vista_estado_resultados_detalle
)
SELECT 
    total_ventas,
    total_costo_ventas,
    ROUND(total_ventas - total_costo_ventas, 2) AS utilidad_bruta,
    total_gastos_operacion,
    ROUND((total_ventas - total_costo_ventas) - total_gastos_operacion, 2) AS utilidad_operacion,
    total_ingresos_financieros,
    total_gastos_financieros,
    ROUND(total_ingresos_financieros - total_gastos_financieros, 2) AS resultado_financiero,
    total_ingresos,
    total_gastos,
    ROUND(total_ingresos - total_gastos, 2) AS utilidad
FROM totales;

-- 5.6. Balance General y Cuadratura (lib/contabilidad.ts -> calcularBalanceGeneral)
CREATE OR REPLACE VIEW vista_balance_general AS
WITH saldos AS (
    SELECT 
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'activo' THEN (total_debe - total_haber) ELSE 0 END), 0.00) AS total_activo,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'pasivo' THEN (total_haber - total_debe) ELSE 0 END), 0.00) AS total_pasivo,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'capital' THEN (total_haber - total_debe) ELSE 0 END), 0.00) AS total_capital_cuentas
    FROM vista_libro_mayor
    WHERE cuenta_tipo IN ('activo', 'pasivo', 'capital')
),
resultado AS (
    SELECT COALESCE(utilidad, 0.00) AS utilidad_ejercicio FROM vista_estado_resultados
)
SELECT 
    ROUND(s.total_activo, 2) AS total_activo,
    ROUND(s.total_pasivo, 2) AS total_pasivo,
    ROUND(s.total_capital_cuentas, 2) AS total_capital_cuentas,
    ROUND(r.utilidad_ejercicio, 2) AS utilidad_ejercicio,
    ROUND(s.total_capital_cuentas + r.utilidad_ejercicio, 2) AS total_capital_contable,
    ROUND(s.total_pasivo + (s.total_capital_cuentas + r.utilidad_ejercicio), 2) AS total_pasivo_mas_capital,
    (ABS(ROUND(s.total_activo, 2) - ROUND(s.total_pasivo + (s.total_capital_cuentas + r.utilidad_ejercicio), 2)) < 0.01) AS cuadra
FROM saldos s
CROSS JOIN resultado r;

-- -----------------------------------------------------------------------------
-- 6. PROCEDIMIENTO DE CIERRE CONTABLE ESTÁNDAR (NO DESTRUCTIVO)
-- -----------------------------------------------------------------------------
-- En lugar de borrar asientos, crea una PARTIDA DE CIERRE real:
-- 1. Carga las cuentas de Ingresos por su saldo (quedan en cero).
-- 2. Abona las cuentas de Gastos por su saldo (quedan en cero).
-- 3. Transfiere la ganancia o pérdida neta a Utilidades Acumuladas (3102).
-- ¡TODA LA HISTORIA SE CONSERVA INTACTA PARA AUDITORÍA!
CREATE OR REPLACE FUNCTION sp_cerrar_ciclo_contable(
    p_ejercicio INT DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INT,
    p_fecha_cierre DATE DEFAULT CURRENT_DATE,
    p_concepto TEXT DEFAULT 'Asiento de liquidación y cierre del ejercicio fiscal'
)
RETURNS UUID AS $$
DECLARE
    v_asiento_cierre_id UUID;
    v_utilidad NUMERIC(14, 2);
    v_total_ingresos NUMERIC(14, 2);
    v_total_gastos NUMERIC(14, 2);
    v_cuenta_capital VARCHAR(20);
    v_linea_idx INT := 1;
    r RECORD;
BEGIN
    -- 1. Obtener totales del estado de resultados
    SELECT 
        COALESCE(total_ingresos, 0.00),
        COALESCE(total_gastos, 0.00),
        COALESCE(utilidad, 0.00)
    INTO v_total_ingresos, v_total_gastos, v_utilidad
    FROM vista_estado_resultados;

    -- 2. Cuenta de capital disponible para absorber la utilidad (3102 o primera activa de capital)
    SELECT codigo INTO v_cuenta_capital 
    FROM catalogo_cuentas 
    WHERE activa = TRUE AND tipo = 'capital'
    ORDER BY CASE WHEN codigo = '3102' THEN 0 ELSE 1 END, codigo ASC
    LIMIT 1;

    IF v_cuenta_capital IS NULL THEN
        RAISE EXCEPTION 'No existe una cuenta de capital activa para transferir la utilidad.';
    END IF;

    -- 3. Insertar la cabecera del Asiento de Cierre (NO SE BORRA NADA)
    INSERT INTO asiento (ejercicio, fecha, concepto, tipo)
    VALUES (p_ejercicio, p_fecha_cierre, p_concepto, 'CIERRE')
    RETURNING id INTO v_asiento_cierre_id;

    -- 4. Cancelar cuentas de Ingresos (Se cargan al Debe para saldo 0)
    FOR r IN (
        SELECT cuenta_codigo, (total_haber - total_debe) AS saldo
        FROM vista_libro_mayor
        WHERE cuenta_tipo = 'ingreso' AND (total_haber - total_debe) > 0
    ) LOOP
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, r.cuenta_codigo, r.saldo, 0.00);
        v_linea_idx := v_linea_idx + 1;
    END LOOP;

    -- 5. Cancelar cuentas de Gastos y Costos (Se abonan al Haber para saldo 0)
    FOR r IN (
        SELECT cuenta_codigo, (total_debe - total_haber) AS saldo
        FROM vista_libro_mayor
        WHERE cuenta_tipo = 'gasto' AND (total_debe - total_haber) > 0
    ) LOOP
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, r.cuenta_codigo, 0.00, r.saldo);
        v_linea_idx := v_linea_idx + 1;
    END LOOP;

    -- 6. Imputar la utilidad o pérdida a la cuenta de Capital
    IF v_utilidad > 0 THEN
        -- Utilidad: abono a Capital
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, v_cuenta_capital, 0.00, v_utilidad);
    ELSIF v_utilidad < 0 THEN
        -- Pérdida: cargo a Capital
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, v_cuenta_capital, ABS(v_utilidad), 0.00);
    END IF;

    -- 7. Registrar en el Historial de Cierres Contables
    INSERT INTO cierre_contable (
        ejercicio, fecha_cierre, concepto,
        total_ingresos, total_gastos, utilidad,
        cuenta_capital_codigo, asiento_cierre_id
    ) VALUES (
        p_ejercicio, p_fecha_cierre, p_concepto,
        v_total_ingresos, v_total_gastos, v_utilidad,
        v_cuenta_capital, v_asiento_cierre_id
    );

    RETURN v_asiento_cierre_id;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 7. DATOS INICIALES (lib/catalogo.ts y ASIENTOS_EJEMPLO de contabilidad-provider)
-- -----------------------------------------------------------------------------

-- 7.1. Catálogo completo de cuentas (48 cuentas oficiales de la app)
INSERT INTO catalogo_cuentas (codigo, nombre, tipo, naturaleza, activa) VALUES
-- 1. Activo (Naturaleza deudora)
-- 11. Activo corriente
('1101', 'Caja general', 'activo', 'deudora', TRUE),
('1102', 'Bancos', 'activo', 'deudora', TRUE),
('1103', 'Cuentas por cobrar', 'activo', 'deudora', TRUE),
('1104', 'Inventario de mercadería', 'activo', 'deudora', TRUE),
('1105', 'IVA crédito fiscal', 'activo', 'deudora', TRUE),
('1106', 'Deudores diversos', 'activo', 'deudora', TRUE),
('1107', 'Papelería y útiles', 'activo', 'deudora', TRUE),
('1108', 'Pagos anticipados', 'activo', 'deudora', TRUE),
-- 12. Activo no corriente
('1201', 'Mobiliario y equipo', 'activo', 'deudora', TRUE),
('1202', 'Equipo de transporte', 'activo', 'deudora', TRUE),
('1203', 'Equipo de cómputo', 'activo', 'deudora', TRUE),
('1204', 'Edificios', 'activo', 'deudora', TRUE),
('1205', 'Terrenos', 'activo', 'deudora', TRUE),
('1206', 'Depreciación acumulada', 'activo', 'deudora', TRUE),

-- 2. Pasivo (Naturaleza acreedora)
-- 21. Pasivo corriente
('2101', 'Cuentas por pagar', 'pasivo', 'acreedora', TRUE),
('2102', 'Préstamos bancarios por pagar', 'pasivo', 'acreedora', TRUE),
('2103', 'IVA débito fiscal', 'pasivo', 'acreedora', TRUE),
('2104', 'Impuestos por pagar', 'pasivo', 'acreedora', TRUE),
('2105', 'Acreedores diversos', 'pasivo', 'acreedora', TRUE),
('2106', 'Sueldos y salarios por pagar', 'pasivo', 'acreedora', TRUE),
('2107', 'Retenciones por pagar', 'pasivo', 'acreedora', TRUE),
-- 22. Pasivo no corriente
('2201', 'Préstamos bancarios a largo plazo', 'pasivo', 'acreedora', TRUE),
('2202', 'Hipotecas por pagar', 'pasivo', 'acreedora', TRUE),

-- 3. Capital contable (Naturaleza acreedora)
('3101', 'Capital social', 'capital', 'acreedora', TRUE),
('3102', 'Utilidades acumuladas', 'capital', 'acreedora', TRUE),
('3103', 'Reserva legal', 'capital', 'acreedora', TRUE),
('3104', 'Pérdidas acumuladas', 'capital', 'acreedora', TRUE),
('3105', 'Donaciones', 'capital', 'acreedora', TRUE),

-- 4. Costos y gastos (Naturaleza deudora)
-- 41. Costo de venta
('4101', 'Costo de venta', 'gasto', 'deudora', TRUE),
('4102', 'Costo de servicios', 'gasto', 'deudora', TRUE),
-- 42. Gastos de operación
('4201', 'Gastos de administración', 'gasto', 'deudora', TRUE),
('4202', 'Gastos de venta', 'gasto', 'deudora', TRUE),
('4203', 'Gastos de depreciación', 'gasto', 'deudora', TRUE),
('4204', 'Gastos de alquiler', 'gasto', 'deudora', TRUE),
('4205', 'Gastos de servicios básicos', 'gasto', 'deudora', TRUE),
('4206', 'Gastos de sueldos y salarios', 'gasto', 'deudora', TRUE),
('4207', 'Gastos de papelería y útiles', 'gasto', 'deudora', TRUE),
('4208', 'Gastos de publicidad', 'gasto', 'deudora', TRUE),
-- 43. Gastos financieros
('4301', 'Gastos financieros', 'gasto', 'deudora', TRUE),
('4302', 'Intereses pagados', 'gasto', 'deudora', TRUE),
('4303', 'Comisiones bancarias', 'gasto', 'deudora', TRUE),

-- 5. Ingresos (Naturaleza acreedora)
-- 51. Ventas y operativos
('5101', 'Ventas', 'ingreso', 'acreedora', TRUE),
('5102', 'Otros ingresos operativos', 'ingreso', 'acreedora', TRUE),
('5103', 'Ingresos por servicios', 'ingreso', 'acreedora', TRUE),
('5104', 'Devoluciones y descuentos sobre ventas', 'ingreso', 'acreedora', TRUE),
-- 52. Financieros
('5201', 'Productos financieros', 'ingreso', 'acreedora', TRUE),
('5202', 'Intereses cobrados', 'ingreso', 'acreedora', TRUE),
('5203', 'Utilidad en venta de activos', 'ingreso', 'acreedora', TRUE)
ON CONFLICT (codigo) DO NOTHING;

-- 7.2. Asientos iniciales de ejemplo
DO $$
DECLARE
    v1 UUID; v2 UUID; v3 UUID; v4 UUID; v5 UUID;
BEGIN
    -- Partida 1: Aporte inicial ($15,000.00)
    INSERT INTO asiento (fecha, concepto, tipo) 
    VALUES ('2026-01-02', 'Aportación inicial de los socios en efectivo y banco.', 'APERTURA') 
    RETURNING id INTO v1;
    INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber) VALUES
    (v1, 1, '1101', 10000.00, 0.00),
    (v1, 2, '1102', 5000.00, 0.00),
    (v1, 3, '3101', 0.00, 15000.00);

    -- Partida 2: Compra de mercadería con IVA crédito fiscal ($4,520.00)
    INSERT INTO asiento (fecha, concepto, tipo) 
    VALUES ('2026-01-05', 'Compra de mercadería al crédito fiscal, pagada con banco.', 'OPERACION') 
    RETURNING id INTO v2;
    INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber) VALUES
    (v2, 1, '1104', 4000.00, 0.00),
    (v2, 2, '1105', 520.00, 0.00),
    (v2, 3, '1102', 0.00, 4520.00);

    -- Partida 3: Venta de mercadería con IVA débito fiscal ($6,780.00)
    INSERT INTO asiento (fecha, concepto, tipo) 
    VALUES ('2026-01-12', 'Venta de mercadería con IVA débito fiscal, cobrada en banco.', 'OPERACION') 
    RETURNING id INTO v3;
    INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber) VALUES
    (v3, 1, '1102', 6780.00, 0.00),
    (v3, 2, '5101', 0.00, 6000.00),
    (v3, 3, '2103', 0.00, 780.00);

    -- Partida 4: Costo de ventas ($3,000.00)
    INSERT INTO asiento (fecha, concepto, tipo) 
    VALUES ('2026-01-12', 'Registro del costo de la mercadería vendida.', 'OPERACION') 
    RETURNING id INTO v4;
    INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber) VALUES
    (v4, 1, '4101', 3000.00, 0.00),
    (v4, 2, '1104', 0.00, 3000.00);

    -- Partida 5: Gastos de administración ($800.00)
    INSERT INTO asiento (fecha, concepto, tipo) 
    VALUES ('2026-01-20', 'Pago de gastos de administración con banco.', 'OPERACION') 
    RETURNING id INTO v5;
    INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber) VALUES
    (v5, 1, '4201', 800.00, 0.00),
    (v5, 2, '1102', 0.00, 800.00);
END $$;
