-- =============================================================================
-- MIGRACIÓN 003: Correlativo Global + Partidas por Ejercicio + No Eliminación en Cascada + Historial de Auditoría
-- =============================================================================

-- 1. MODIFICAR TABLA ASIENTO: Correlativo Global, Ejercicio Anual, Estado y Auditoría
ALTER TABLE asiento
    ADD COLUMN IF NOT EXISTS correlativo_global INT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'APLICADO',
    ADD COLUMN IF NOT EXISTS anulado_en TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS motivo_anulacion TEXT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_asiento_estado'
    ) THEN
        ALTER TABLE asiento ADD CONSTRAINT chk_asiento_estado CHECK (estado IN ('APLICADO', 'ANULADO'));
    END IF;
END $$;

-- 2. REINICIO DE PARTIDAS POR AÑO (UNIQUE por ejercicio y numero)
ALTER TABLE asiento DROP CONSTRAINT IF EXISTS asiento_numero_key;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_asiento_ejercicio_numero'
    ) THEN
        ALTER TABLE asiento ADD CONSTRAINT uq_asiento_ejercicio_numero UNIQUE (ejercicio, numero);
    END IF;
END $$;

-- 3. ELIMINAR CASCADA EN ASIENTO_LINEA (ON DELETE RESTRICT por auditoría)
ALTER TABLE asiento_linea DROP CONSTRAINT IF EXISTS asiento_linea_asiento_id_fkey;
ALTER TABLE asiento_linea
    ADD CONSTRAINT asiento_linea_asiento_id_fkey
    FOREIGN KEY (asiento_id) REFERENCES asiento(id) ON DELETE RESTRICT;

-- 4. TABLA DE HISTORIAL / AUDITORÍA CONTABLE
CREATE TABLE IF NOT EXISTS asiento_historial (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asiento_id UUID NOT NULL REFERENCES asiento(id) ON DELETE RESTRICT,
    accion VARCHAR(20) NOT NULL CHECK (accion IN ('CREACION', 'MODIFICACION', 'ANULACION', 'CIERRE')),
    ejercicio INT NOT NULL,
    numero INT NOT NULL,
    concepto TEXT,
    total_debe NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_haber NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    motivo TEXT,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historial_asiento ON asiento_historial(asiento_id);
CREATE INDEX IF NOT EXISTS idx_historial_fecha ON asiento_historial(creado_en);
CREATE INDEX IF NOT EXISTS idx_historial_accion ON asiento_historial(accion);

-- 5. FUNCIÓN: Obtener próximo número de partida para el ejercicio fiscal
CREATE OR REPLACE FUNCTION fn_proximo_numero_asiento(p_ejercicio INT)
RETURNS INT AS $$
BEGIN
    RETURN COALESCE((SELECT MAX(numero) FROM asiento WHERE ejercicio = p_ejercicio), 0) + 1;
END;
$$ LANGUAGE plpgsql;

-- 6. FUNCIÓN: Anulación contable de un asiento (Auditoría sin DELETE)
CREATE OR REPLACE FUNCTION sp_anular_asiento(
    p_asiento_id UUID,
    p_motivo TEXT DEFAULT 'Anulación contable por corrección/auditoría'
)
RETURNS BOOLEAN AS $$
DECLARE
    v_ejercicio INT;
    v_numero INT;
    v_concepto TEXT;
    v_total_debe NUMERIC(14, 2);
    v_total_haber NUMERIC(14, 2);
    v_estado VARCHAR(20);
BEGIN
    SELECT ejercicio, numero, concepto, estado 
    INTO v_ejercicio, v_numero, v_concepto, v_estado
    FROM asiento
    WHERE id = p_asiento_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'El asiento con ID % no existe.', p_asiento_id;
    END IF;

    IF v_estado = 'ANULADO' THEN
        RAISE EXCEPTION 'La partida #% del ejercicio % ya se encuentra anulada.', v_numero, v_ejercicio;
    END IF;

    SELECT COALESCE(SUM(debe), 0.00), COALESCE(SUM(haber), 0.00)
    INTO v_total_debe, v_total_haber
    FROM asiento_linea
    WHERE asiento_id = p_asiento_id;

    -- 1. Marcar asiento como anulado (sin DELETE físico)
    UPDATE asiento
    SET estado = 'ANULADO',
        anulado_en = CURRENT_TIMESTAMP,
        motivo_anulacion = p_motivo
    WHERE id = p_asiento_id;

    -- 2. Registrar traza en el historial de auditoría
    INSERT INTO asiento_historial (
        asiento_id, accion, ejercicio, numero, concepto,
        total_debe, total_haber, motivo
    ) VALUES (
        p_asiento_id, 'ANULACION', v_ejercicio, v_numero, v_concepto,
        v_total_debe, v_total_haber, p_motivo
    );

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- 7. REEMPLAZAR sp_cerrar_ciclo_contable con numeración por año y registro en historial
CREATE OR REPLACE FUNCTION sp_cerrar_ciclo_contable(
    p_ejercicio INT DEFAULT EXTRACT(YEAR FROM CURRENT_DATE)::INT,
    p_fecha_cierre DATE DEFAULT CURRENT_DATE,
    p_concepto TEXT DEFAULT 'Asiento de liquidación y cierre del ejercicio fiscal'
)
RETURNS UUID AS $$
DECLARE
    v_asiento_cierre_id UUID;
    v_proximo_numero INT;
    v_utilidad NUMERIC(14, 2);
    v_total_ingresos NUMERIC(14, 2);
    v_total_gastos NUMERIC(14, 2);
    v_cuenta_capital VARCHAR(20);
    v_linea_idx INT := 1;
    r RECORD;
BEGIN
    -- 1. Obtener totales del estado de resultados
    SELECT 
        COALESCE(total_ingresos, 0.00),
        COALESCE(total_gastos, 0.00),
        COALESCE(utilidad, 0.00)
    INTO v_total_ingresos, v_total_gastos, v_utilidad
    FROM vista_estado_resultados;

    -- 2. Cuenta de capital disponible para absorber la utilidad
    SELECT codigo INTO v_cuenta_capital 
    FROM catalogo_cuentas 
    WHERE activa = TRUE AND tipo = 'capital'
    ORDER BY CASE WHEN codigo = '3102' THEN 0 ELSE 1 END, codigo ASC
    LIMIT 1;

    IF v_cuenta_capital IS NULL THEN
        RAISE EXCEPTION 'No existe una cuenta de capital activa para transferir la utilidad.';
    END IF;

    -- 3. Obtener número consecutivo para este ejercicio fiscal específico
    v_proximo_numero := fn_proximo_numero_asiento(p_ejercicio);

    -- 4. Insertar cabecera del Asiento de Cierre (NO SE BORRA NADA)
    INSERT INTO asiento (ejercicio, numero, fecha, concepto, tipo, estado)
    VALUES (p_ejercicio, v_proximo_numero, p_fecha_cierre, p_concepto, 'CIERRE', 'APLICADO')
    RETURNING id INTO v_asiento_cierre_id;

    -- 5. Cancelar cuentas de Ingresos (Se cargan al Debe para saldo 0)
    FOR r IN (
        SELECT cuenta_codigo, (total_haber - total_debe) AS saldo
        FROM vista_libro_mayor
        WHERE cuenta_tipo = 'ingreso' AND (total_haber - total_debe) > 0
    ) LOOP
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, r.cuenta_codigo, r.saldo, 0.00);
        v_linea_idx := v_linea_idx + 1;
    END LOOP;

    -- 6. Cancelar cuentas de Gastos y Costos (Se abonan al Haber para saldo 0)
    FOR r IN (
        SELECT cuenta_codigo, (total_debe - total_haber) AS saldo
        FROM vista_libro_mayor
        WHERE cuenta_tipo = 'gasto' AND (total_debe - total_haber) > 0
    ) LOOP
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, r.cuenta_codigo, 0.00, r.saldo);
        v_linea_idx := v_linea_idx + 1;
    END LOOP;

    -- 7. Imputar la utilidad o pérdida a la cuenta de Capital
    IF v_utilidad > 0 THEN
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, v_cuenta_capital, 0.00, v_utilidad);
    ELSIF v_utilidad < 0 THEN
        INSERT INTO asiento_linea (asiento_id, linea_numero, cuenta_codigo, debe, haber)
        VALUES (v_asiento_cierre_id, v_linea_idx, v_cuenta_capital, ABS(v_utilidad), 0.00);
    END IF;

    -- 8. Registrar en el Historial de Cierres Contables
    INSERT INTO cierre_contable (
        ejercicio, fecha_cierre, concepto,
        total_ingresos, total_gastos, utilidad,
        cuenta_capital_codigo, asiento_cierre_id
    ) VALUES (
        p_ejercicio, p_fecha_cierre, p_concepto,
        v_total_ingresos, v_total_gastos, v_utilidad,
        v_cuenta_capital, v_asiento_cierre_id
    );

    -- 9. Registrar en Historial de Auditoría
    INSERT INTO asiento_historial (
        asiento_id, accion, ejercicio, numero, concepto,
        total_debe, total_haber, motivo
    ) VALUES (
        v_asiento_cierre_id, 'CIERRE', p_ejercicio, v_proximo_numero, p_concepto,
        v_total_ingresos, v_total_ingresos, 'Liquidación y cierre formal del ejercicio fiscal'
    );

    RETURN v_asiento_cierre_id;
END;
$$ LANGUAGE plpgsql;

-- 8. ACTUALIZAR VISTAS PARA QUE SÓLO CONSIDEREN ASIENTOS APLICADOS
DROP VIEW IF EXISTS vista_libro_diario CASCADE;
DROP VIEW IF EXISTS vista_libro_mayor CASCADE;
DROP VIEW IF EXISTS vista_balance_comprobacion CASCADE;
DROP VIEW IF EXISTS vista_estado_resultados_detalle CASCADE;
DROP VIEW IF EXISTS vista_estado_resultados CASCADE;
DROP VIEW IF EXISTS vista_balance_general CASCADE;

CREATE OR REPLACE VIEW vista_libro_diario AS
SELECT 
    a.id AS asiento_id,
    a.correlativo_global,
    a.numero AS partida_numero,
    a.ejercicio,
    a.fecha,
    a.concepto,
    a.tipo AS tipo_asiento,
    a.estado AS estado_asiento,
    a.anulado_en,
    a.motivo_anulacion,
    al.linea_numero,
    c.codigo AS cuenta_codigo,
    c.nombre AS cuenta_nombre,
    c.tipo AS cuenta_tipo,
    c.naturaleza AS cuenta_naturaleza,
    al.debe,
    al.haber
FROM asiento a
JOIN asiento_linea al ON a.id = al.asiento_id
JOIN catalogo_cuentas c ON al.cuenta_codigo = c.codigo
ORDER BY a.fecha DESC, a.numero DESC, al.linea_numero ASC;

CREATE OR REPLACE VIEW vista_libro_mayor AS
SELECT 
    c.codigo AS cuenta_codigo,
    c.nombre AS cuenta_nombre,
    c.tipo AS cuenta_tipo,
    c.naturaleza AS cuenta_naturaleza,
    c.activa,
    ROUND(SUM(al.debe), 2) AS total_debe,
    ROUND(SUM(al.haber), 2) AS total_haber,
    ROUND(SUM(al.debe) - SUM(al.haber), 2) AS saldo_neto,
    CASE 
        WHEN ROUND(SUM(al.debe) - SUM(al.haber), 2) > 0 THEN 'deudora'
        WHEN ROUND(SUM(al.debe) - SUM(al.haber), 2) < 0 THEN 'acreedora'
        ELSE NULL 
    END AS naturaleza_saldo,
    CASE 
        WHEN c.naturaleza = 'deudora' THEN ROUND(SUM(al.debe) - SUM(al.haber), 2)
        ELSE ROUND(SUM(al.haber) - SUM(al.debe), 2)
    END AS saldo_normalizado
FROM catalogo_cuentas c
JOIN asiento_linea al ON c.codigo = al.cuenta_codigo
JOIN asiento a ON al.asiento_id = a.id
WHERE a.estado = 'APLICADO'
GROUP BY c.codigo, c.nombre, c.tipo, c.naturaleza, c.activa
HAVING SUM(al.debe) <> 0 OR SUM(al.haber) <> 0;

-- 8.1. Balance de Comprobación
CREATE OR REPLACE VIEW vista_balance_comprobacion AS
SELECT 
    cuenta_codigo,
    cuenta_nombre,
    cuenta_tipo,
    total_debe,
    total_haber,
    CASE WHEN saldo_neto > 0 THEN saldo_neto ELSE 0.00 END AS saldo_deudor,
    CASE WHEN saldo_neto < 0 THEN ABS(saldo_neto) ELSE 0.00 END AS saldo_acreedor
FROM vista_libro_mayor
ORDER BY cuenta_codigo ASC;

-- 8.2. Detalle Estado de Resultados
CREATE OR REPLACE VIEW vista_estado_resultados_detalle AS
SELECT 
    cuenta_codigo,
    cuenta_nombre,
    cuenta_tipo,
    CASE 
        WHEN cuenta_tipo = 'ingreso' AND LEFT(cuenta_codigo, 2) = '52' THEN 'ingresosFinancieros'
        WHEN cuenta_tipo = 'ingreso' THEN 'ventas'
        WHEN cuenta_tipo = 'gasto' AND LEFT(cuenta_codigo, 2) = '41' THEN 'costoVentas'
        WHEN cuenta_tipo = 'gasto' AND LEFT(cuenta_codigo, 2) = '43' THEN 'gastosFinancieros'
        WHEN cuenta_tipo = 'gasto' THEN 'gastosOperacion'
        ELSE NULL 
    END AS subgrupo,
    CASE 
        WHEN cuenta_tipo = 'ingreso' THEN ROUND(total_haber - total_debe, 2)
        WHEN cuenta_tipo = 'gasto' THEN ROUND(total_debe - total_haber, 2)
        ELSE 0.00
    END AS monto
FROM vista_libro_mayor
WHERE cuenta_tipo IN ('ingreso', 'gasto');

-- 8.3. Resumen Estado de Resultados en Cascada
CREATE OR REPLACE VIEW vista_estado_resultados AS
WITH totales AS (
    SELECT 
        COALESCE(SUM(CASE WHEN subgrupo = 'ventas' THEN monto ELSE 0 END), 0.00) AS total_ventas,
        COALESCE(SUM(CASE WHEN subgrupo = 'costoVentas' THEN monto ELSE 0 END), 0.00) AS total_costo_ventas,
        COALESCE(SUM(CASE WHEN subgrupo = 'gastosOperacion' THEN monto ELSE 0 END), 0.00) AS total_gastos_operacion,
        COALESCE(SUM(CASE WHEN subgrupo = 'ingresosFinancieros' THEN monto ELSE 0 END), 0.00) AS total_ingresos_financieros,
        COALESCE(SUM(CASE WHEN subgrupo = 'gastosFinancieros' THEN monto ELSE 0 END), 0.00) AS total_gastos_financieros,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'ingreso' THEN monto ELSE 0 END), 0.00) AS total_ingresos,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'gasto' THEN monto ELSE 0 END), 0.00) AS total_gastos
    FROM vista_estado_resultados_detalle
)
SELECT 
    total_ventas,
    total_costo_ventas,
    ROUND(total_ventas - total_costo_ventas, 2) AS utilidad_bruta,
    total_gastos_operacion,
    ROUND((total_ventas - total_costo_ventas) - total_gastos_operacion, 2) AS utilidad_operacion,
    total_ingresos_financieros,
    total_gastos_financieros,
    ROUND(total_ingresos_financieros - total_gastos_financieros, 2) AS resultado_financiero,
    total_ingresos,
    total_gastos,
    ROUND(total_ingresos - total_gastos, 2) AS utilidad
FROM totales;

-- 8.4. Balance General y Cuadratura
CREATE OR REPLACE VIEW vista_balance_general AS
WITH saldos AS (
    SELECT 
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'activo' THEN (total_debe - total_haber) ELSE 0 END), 0.00) AS total_activo,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'pasivo' THEN (total_haber - total_debe) ELSE 0 END), 0.00) AS total_pasivo,
        COALESCE(SUM(CASE WHEN cuenta_tipo = 'capital' THEN (total_haber - total_debe) ELSE 0 END), 0.00) AS total_capital_cuentas
    FROM vista_libro_mayor
    WHERE cuenta_tipo IN ('activo', 'pasivo', 'capital')
),
resultado AS (
    SELECT COALESCE(utilidad, 0.00) AS utilidad_ejercicio FROM vista_estado_resultados
)
SELECT 
    ROUND(s.total_activo, 2) AS total_activo,
    ROUND(s.total_pasivo, 2) AS total_pasivo,
    ROUND(s.total_capital_cuentas, 2) AS total_capital_cuentas,
    ROUND(r.utilidad_ejercicio, 2) AS utilidad_ejercicio,
    ROUND(s.total_capital_cuentas + r.utilidad_ejercicio, 2) AS total_capital_contable,
    ROUND(s.total_pasivo + (s.total_capital_cuentas + r.utilidad_ejercicio), 2) AS total_pasivo_mas_capital,
    (ABS(ROUND(s.total_activo, 2) - ROUND(s.total_pasivo + (s.total_capital_cuentas + r.utilidad_ejercicio), 2)) < 0.01) AS cuadra
FROM saldos s
CROSS JOIN resultado r;
